const questions = [
  {
    id: 0,
    question: "¿Dónde lleva la tilde una palabra esdrújula?",
    answers: [
      { answer: "En la primera sílaba.", isCorrect: false },
      { answer: "En la antepenúltima sílaba.", isCorrect: true },
      { answer: "En la última sílaba.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 1,
    question:
      "¿Cómo se lee la hora si la aguja chica del reloj esta en las 4 y la larga también?",
    answers: [
      { answer: "Las veinte y veinte o las 20:20hs.", isCorrect: false },
      { answer: "Las veinte y cuarto o las 20:15hs.", isCorrect: false },
      { answer: "Las cuatro y veinte o las 16:20hs.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 2,
    question:
      "¿Cómo se llaman los animales que tienen un esqueleto articulado?",
    answers: [
      { answer: "Invertebrados.", isCorrect: false },
      { answer: "Vertebrados.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 3,
    question: "¿Cómo se llama un polígono de 3 lados?",
    answers: [
      { answer: "Cuadrado.", isCorrect: false },
      { answer: "Triángulo.", isCorrect: true },
      { answer: "Pentágono.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 4,
    question: "¿Cuántos minutos tiene una hora?",
    answers: [
      { answer: "60.", isCorrect: true },
      { answer: "120.", isCorrect: false },
      { answer: "90.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 5,
    question: "¿Cómo se llama un polígono de 5 lados?",
    answers: [
      { answer: "Pentágono.", isCorrect: true },
      { answer: "Rectángulo.", isCorrect: false },
      { answer: "Hexágono.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 6,
    question: "¿Cómo se llama el triángulo que tiene 3 lados iguales?",
    answers: [
      { answer: "Isosceles.", isCorrect: false },
      { answer: "Escaleno.", isCorrect: false },
      { answer: "Equilátero.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 7,
    question: "¿Qué tipo de palabra es murciélago?",
    answers: [
      { answer: "Grave.", isCorrect: false },
      { answer: "Esdrújula.", isCorrect: true },
      { answer: "Aguda.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 8,
    question: '¿Cómo se dice en ingles "buenas tardes"?',
    answers: [
      { answer: "Good evening.", isCorrect: false },
      { answer: "Good night.", isCorrect: false },
      { answer: "Good afternoon.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 9,
    question: "¿Cómo se llama la línea que ponemos encima de la sílaba tónica?",
    answers: [
      { answer: "Tilde.", isCorrect: true },
      { answer: "Acento.", isCorrect: false },
      { answer: "Diéresis.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 10,
    question: "¿Cuál es el resultado de 9x9?",
    answers: [
      { answer: "49.", isCorrect: false },
      { answer: "81.", isCorrect: true },
      { answer: "74.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 11,
    question: "¿Cómo se llama el lugar donde se escriben las notas musicales?",
    answers: [
      { answer: "Notero.", isCorrect: false },
      { answer: "Anagrama.", isCorrect: false },
      { answer: "Pentagrama.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 12,
    question: "¿Cómo se llama un polígono de 6 lados?",
    answers: [
      { answer: "Hexágono.", isCorrect: true },
      { answer: "Pentágono.", isCorrect: false },
      { answer: "Octágono.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 13,
    question:
      "¿Cómo se llaman los animales que solo se alimentan de vegetales y plantas?",
    answers: [
      { answer: "Omnívoros.", isCorrect: false },
      { answer: "Carnívoros.", isCorrect: false },
      { answer: "Herbívoros.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 14,
    question: "¿Cuantos continentes tiene la tierra?",
    answers: [
      { answer: "6.", isCorrect: false },
      { answer: "8.", isCorrect: false },
      { answer: "7.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 15,
    question: "¿Cuál es la capital de Bulgaria?",
    answers: [
      { answer: "Sofía.", isCorrect: true },
      { answer: "Candela.", isCorrect: false },
      { answer: "Bulgaria.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 16,
    question: "¿Cuantos océanos tiene la tierra?",
    answers: [
      { answer: "6.", isCorrect: false },
      { answer: "5.", isCorrect: true },
      { answer: "4.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 17,
    question:
      "¿Cómo se llama la línea imaginaria que divide la tierra por la mitad?",
    answers: [
      { answer: "Meridiano de Ecuador.", isCorrect: false },
      { answer: "Meridiano de Greenwich.", isCorrect: false },
      { answer: "Ecuador.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 18,
    question: "¿Cada cuantos años es año bisiesto?",
    answers: [
      { answer: "5.", isCorrect: false },
      { answer: "3.", isCorrect: false },
      { answer: "4.", isCorrect: true },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 19,
    question: "¿Por dónde sale el sol?",
    answers: [
      { answer: "Este.", isCorrect: true },
      { answer: "Oeste.", isCorrect: false },
      { answer: "Norte.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
  {
    id: 20,
    question: "¿En qué continente está Ucrania?",
    answers: [
      { answer: "America del norte.", isCorrect: false },
      { answer: "Europa.", isCorrect: true },
      { answer: "Asia.", isCorrect: false },
    ],
    points_correct: 105,
    easy_mode_time_response: 60,
    medium_mode_time_response: 30,
    hard_mode_time_response: 15,
  },
];

export default questions;
