import Head from "next/head";
import "../styles/globals.css";
import { UtilsProvider } from "../utils/Utils";

function MyApp({ Component, pageProps }) {
  return (
    <UtilsProvider>
      <Head>
        <title>Preguntas y respuestas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </UtilsProvider>
  );
}

export default MyApp;
